package enums;

public enum TipoLog {
	CREAR_OFERTA, BORRAR_OFERTA, CONTRAOFERTA, ACEPTAR_CONTRA, CANCELAR_OFERTA, TRANSFERENCIA, COMPRA, REEMBOLSO, BORRAR_OFERTA_VENDEDOR, ACEPTAR_CONTRAOFERTA, VENTA_CONCRETADA, BORRAR_OFERTA_ADMIN, COMPRAR_OFERTA
}
